# Build on master
# build, version and package for deployment
-
  branches:
    only:
      - master

  version: 0.1.{build}

  skip_tags: true

  build_script:
    - cmd: build.cmd package

  artifacts:
    - path: dist\hakudu.exe


# Build on development branches and pull requests
# build only
-
  version: 0.1.{build}

  pull_requests:
    do_not_increment_build_number: true

  skip_tags: true

  build_script:
    - cmd: build.cmd build
